"use strict";
const q=(s)=>document.querySelector(s),status=q("#status");
const headers=(mutation=false)=>Object.assign({Authorization:"Bearer "+q("#token").value,"Content-Type":"application/json"},mutation?{Origin:location.origin}:{});
async function api(path,options={}){const response=await fetch(path,{...options,headers:headers(Boolean(options.method))});if(!response.ok)throw new Error(await response.text()||`Request failed (${response.status})`);return response.status===204?null:response.json()}
function rows(id,items,cells){const body=q(id);body.replaceChildren();for(const item of items){const row=document.createElement("tr");for(const value of cells(item)){const cell=document.createElement("td");cell.textContent=value??"";row.append(cell)}body.append(row)}}
async function refresh(){status.textContent="";try{const [targets,credentials,policies,bindings]=await Promise.all([api("/api/v1/admin/rdp/targets"),api("/api/v1/admin/credentials"),api("/api/v1/admin/rdp/policies"),api("/api/v1/admin/rdp/bindings")]);rows("#targets",targets,x=>[x.name,`${x.hostname}:${x.port}`,x.network_zone,x.enabled]);rows("#credentials",credentials,x=>[x.name,x.provider,x.external_ref,x.status]);rows("#policies",policies,x=>[x.name,x.priority,`${x.maximum_duration_seconds}s`,x.enabled]);rows("#bindings",bindings,x=>[`${x.subject_type}:${x.subject_id}`,x.target_id,x.policy_id,x.priority])}catch(error){status.textContent=error.message}}
q("#refresh").addEventListener("click",refresh);
q("#target-form").addEventListener("submit",async event=>{event.preventDefault();const f=new FormData(event.currentTarget);try{await api("/api/v1/admin/rdp/targets",{method:"POST",body:JSON.stringify({name:f.get("name"),hostname:f.get("hostname"),port:3389,domain:f.get("domain"),certificate_fingerprint:f.get("certificate_fingerprint"),network_zone:f.get("network_zone"),enabled:f.get("enabled")==="on"})});event.currentTarget.reset();await refresh()}catch(error){status.textContent=error.message}});
q("#credential-form").addEventListener("submit",async event=>{event.preventDefault();const f=new FormData(event.currentTarget);try{await api("/api/v1/admin/credentials",{method:"POST",body:JSON.stringify(Object.fromEntries(f))});event.currentTarget.reset();await refresh()}catch(error){status.textContent=error.message}});
